import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { getDayType } from './dateUtils';
import { normalizeName } from './staffUtils';

export const exportShiftToPDF = async (staffName: string, requests: any[], currentYear: number, currentMonth: number) => {
  const daysInMonth = new Date(currentYear, currentMonth + 1, 0).getDate();
  const monthName = `${currentYear}年 ${currentMonth + 1}月`;
  const normalizedTargetName = normalizeName(staffName);
  
  const formatDateKey = (date: Date) => {
    const y = date.getFullYear();
    const m = String(date.getMonth() + 1).padStart(2, '0');
    const d = String(date.getDate()).padStart(2, '0');
    return `${y}-${m}-${d}`;
  };

  const leaveTypes = ['年休', '有給休暇', '時間休', '時間給', '看護休暇', '振替', '夏季休暇', '午前休', '午後休', '特休', '休暇', '年休', '欠勤', '長期休暇', '全休', 'シフト休', '公休', '午前振替', '午後振替'];

  let rowsHtml = '';
  for (let d = 1; d <= daysInMonth; d++) {
    const date = new Date(currentYear, currentMonth, d);
    const dateStr = formatDateKey(date);
    const dayName = ['日', '月', '火', '水', '木', '金', '土'][date.getDay()];
    const type = getDayType(date);
    
    // 申請データを取得（承認済み優先、なければ申請中も探す）
    const allUserReqs = requests.filter(r => normalizeName(r.staffName) === normalizedTargetName && r.date === dateStr);
    const approvedReq = allUserReqs.find(r => r.status === 'approved');
    const pendingReq = allUserReqs.find(r => r.status === 'pending');
    const req = approvedReq || pendingReq;

    let isWork = false;
    if (req) {
      if (req.type === '出勤') isWork = true;
      else if (leaveTypes.includes(req.type)) isWork = false;
      else isWork = (type === 'weekday');
    } else {
      isWork = (type === 'weekday');
    }
    
    // Style for holiday rows
    const rowClass = type === 'sat' ? 'sat-row' : (type === 'sun' || type === 'holiday') ? 'holiday-row' : '';
    const statusText = isWork ? '出勤' : (req?.type || '公休');
    let statusClass = isWork ? 'status-work' : 'status-off';
    if (statusText.includes('振替')) statusClass = 'status-transfer';

    rowsHtml += `
      <tr class="${rowClass}">
        <td>${d}日 (${dayName})</td>
        <td><span class="status-badge ${statusClass}">${statusText}</span></td>
        <td>${req?.details?.note || ''}</td>
      </tr>
    `;
  }

  const html = `
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
        <style>
          body { font-family: 'Helvetica Neue', Helvetica, 'Hiragino Sans', 'Hiragino Kaku Gothic ProN', Arial, sans-serif; padding: 20px; color: #1e293b; background-color: #fff; }
          h1 { color: #0f172a; border-left: 5px solid #38bdf8; padding-left: 15px; margin-bottom: 25px; font-size: 26px; }
          .header-info { margin-bottom: 30px; background-color: #f8fafc; padding: 20px; border-radius: 12px; border: 1px solid #f1f5f9; }
          .header-info p { margin: 8px 0; font-size: 16px; }
          table { width: 100%; border-collapse: separate; border-spacing: 0; margin-top: 10px; border: 1px solid #f1f5f9; border-radius: 12px; overflow: hidden; }
          th, td { padding: 14px 16px; text-align: left; border-bottom: 1px solid #f1f5f9; }
          th { background-color: #f8fafc; color: #64748b; font-weight: bold; font-size: 13px; text-transform: uppercase; letter-spacing: 0.05em; border-bottom-width: 2px; }
          tr:last-child td { border-bottom: none; }
          .holiday-row { background-color: #fff1f2; }
          .sat-row { background-color: #f0f9ff; }
          .status-badge { padding: 4px 10px; border-radius: 100px; font-weight: bold; font-size: 12px; display: inline-block; }
          .status-work { background-color: #e0f2fe; color: #0369a1; }
          .status-off { background-color: #f8fafc; color: #64748b; }
          .status-transfer { background-color: #f0f9ff; color: #b45309; border: 1.5px solid #facc15; }
          .footer { margin-top: 40px; font-size: 12px; color: #94a3b8; text-align: center; font-style: italic; }
        </style>
      </head>
      <body>
        <h1>勤務シフト表</h1>
        <div class="header-info">
          <p><strong>スタッフ氏名:</strong> ${staffName}</p>
          <p><strong>対象期間:</strong> ${monthName}</p>
        </div>
        <table>
          <thead>
            <tr>
              <th>日付</th>
              <th>シフト</th>
              <th>備考</th>
            </tr>
          </thead>
          <tbody>
            ${rowsHtml}
          </tbody>
        </table>
        <div class="footer">
          Generated by ShiftManager App
        </div>
      </body>
    </html>
  `;

  try {
    const { uri } = await Print.printToFileAsync({ html });
    await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
  } catch (error) {
    console.error('PDF Export Error:', error);
    throw error;
  }
};
